# SPDX-FileCopyrightText: Copyright (C) 2022-2026 Cosmo Tech
# SPDX-License-Identifier: MIT
apiVersion: v2
name: cosmotech-business-webapp
description: Cosmo Tech Business Web Application
type: application
version: 0.2.2
home: https://cosmotech.com
sources:
  - https://github.com/Cosmo-Tech/azure-sample-webapp
