apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resolutionrequests.resolution.tekton.dev
  labels:
    resolution.tekton.dev/release: devel
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: '{{ include "tekton-pipelines.fullname" . }}-webhook'
          namespace: '{{ .Release.Namespace }}'
      conversionReviewVersions:
      - v1alpha1
      - v1beta1
  group: resolution.tekton.dev
  names:
    categories:
    - tekton
    - tekton-pipelines
    kind: ResolutionRequest
    plural: resolutionrequests
    shortNames:
    - resolutionrequest
    - resolutionrequests
    singular: resolutionrequest
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.conditions[?(@.type=='Succeeded')].status
      name: Succeeded
      type: string
    - jsonPath: .status.conditions[?(@.type=='Succeeded')].reason
      name: Reason
      type: string
    deprecated: true
    name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: false
    subresources:
      status: {}
  - additionalPrinterColumns:
    - jsonPath: .metadata.ownerReferences[0].kind
      name: OwnerKind
      type: string
    - jsonPath: .metadata.ownerReferences[0].name
      name: Owner
      type: string
    - jsonPath: .status.conditions[?(@.type=='Succeeded')].status
      name: Succeeded
      type: string
    - jsonPath: .status.conditions[?(@.type=='Succeeded')].reason
      name: Reason
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: StartTime
      type: string
    - jsonPath: .status.conditions[?(@.type=='Succeeded')].lastTransitionTime
      name: EndTime
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []