apiVersion: v1
kind: Service
metadata:
  name: {{ include "tekton-pipelines.fullname" . }}-tekton-events-controller
  labels:
    app: tekton-events-controller
    app.kubernetes.io/component: events
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: v0.65.0
    version: v0.65.0
  {{- include "tekton-pipelines.labels" . | nindent 4 }}
spec:
  type: {{ .Values.tektonEventsController.type }}
  selector:
    app.kubernetes.io/component: events
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: events
    app.kubernetes.io/part-of: tekton-pipelines
  {{- include "tekton-pipelines.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.tektonEventsController.ports | toYaml | nindent 2 }}