# SPDX-FileCopyrightText: Copyright (C) 2022-2026 Cosmo Tech
# SPDX-License-Identifier: MIT
name: Modeling API / Restart deployment

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Docker image tag that was updated"
        required: true
        type: choice
        options:
          - continuous
          - nightly

permissions:
  contents: read
  id-token: write

jobs:
  restart:
    runs-on: ubuntu-latest
    environment: modeling_api_warp
    steps:
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/use-kubelogin@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          kubelogin-version: 'latest'

      - uses: azure/aks-set-context@v4
        with:
          cluster-name: "${{ vars.CLUSTER_NAME }}"
          resource-group: "${{ vars.CLUSTER_RESOURCE_GROUP }}"
          use-kubelogin: true

      - name: Check cluster availability
        id: cluster_availability
        continue-on-error: true
        run: |
          kubectl version

      - name: Restart deployment
        if: ${{ steps.cluster_availability.outcome == 'success' }}
        run: >
          kubectl rollout restart
          --namespace ${{ vars.CLUSTER_NAMESPACE }}
          deployment/cosmotech-modeling-api-${{ inputs.imageTag }}

      - name: Wait for restart to finish
        if: ${{ steps.cluster_availability.outcome == 'success' }}
        run: >
          kubectl rollout status
          --namespace ${{ vars.CLUSTER_NAMESPACE }}
          --timeout=10m
          deployment/cosmotech-modeling-api-${{ inputs.imageTag }}
